env:
  browser: true
  es2021: true
root: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
plugins:
  - react-refresh
parser: '@typescript-eslint/parser'
rules:
  no-tabs: 0
  react-refresh/only-export-components: 1
  react/react-in-jsx-scope: 0
ignorePatterns:
  - node_modules/
  - build/
  - vite*
